### ISSUE TITLE
Nice job!

### ISSUE THREAD

**Issue by mfkl** [spmn/vlc-win10smtc#1]
Hi there,

Well done! Would you like to contribute this upstream? https://code.videolan.org/videolan/vlc

We'd love to have your contribution!

**Comment by spmn** [comment]
Hi, I'd like to see the code upstreamed, but for now I don't have the time to setup the environment and toolchain in order to get it working with the main tree.

Anyway, the code is released under GPL, so you are free to contribute it upstream.
