### ISSUE TITLE
Implement thumbnails?

### ISSUE THREAD

**Issue by Borgotto** [spmn/vlc-win10smtc#2]
Any chance we'll ever see that `// TODO: use artwork provided by ID3tag (if exists)` removed?

I understand if this project is not in your interests anymore, it's a good one nonetheless.

**Comment by spmn** [comment]
There is always a chance for that to happen, but I wouldnt keep my hopes up 😄 

Jokes aside, probably not. Unfortunately, I don't know that well the VLC API and the newish WinRT APIs needed to make this integration happen. I am open to PRs though

**Comment by Borgotto** [comment]
No worries, I actually didn't expect a reply haha.
I'll see if I have some spare time next year

**Comment by ungive** [comment]
Would love to see it happen too!

I've been sitting on the other end of it (reading metadata with WinRT) for while now while working on [Music Presence](https://github.com/ungive/discord-music-presence), I might look into it too, if I find the time. Would be a useful experience.

**Comment by TheUnifox** [comment]
made a pr with it, and I've tested it works to rport either a thumbnail in cache, or default one if none exist

**Comment by spmn** [comment]
Closing as done #6

Thanks again, @TheUnifox
