### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by MaxineMaxie** [spmn/vlc-win10smtc#4]
After installing the plugin and enabling it in VLC's settings, the Windows media controls continue to show no signs of VLC's existence.
I am not sure whether I am doing something wrong or if the plugin just isn't working, help would be very much appreciated.

![image](https://github.com/spmn/vlc-win10smtc/assets/94768673/64b0c65f-0296-4f6e-915c-51c200b580f3)

![image](https://github.com/spmn/vlc-win10smtc/assets/94768673/91955e4b-0daa-47d3-a084-60d0d69d716b)

**Comment by spmn** [comment]
I hate to be that guy, but _it still works on my machine_.

I've just tested it with the latest x64 VLC release (3.0.21) and everything seems alright. Could you confirm that you're also running the latest x64 build of VLC? Also, maybe my plugin is not compatible with some of your VLC settings, so could you also try it with a clean install of VLC?

**Comment by MaxineMaxie** [comment]
I'm unsure of how (could be that it requires a PC restart but idk) but it works now!
so uh, if you're having issues restart your PC
