### ISSUE TITLE
Error 0x80004005 when copying DLL from extracted folder to plugins/misc

### ISSUE THREAD

**Issue by mysticmst** [spmn/vlc-win10smtc#8]
![image](https://github.com/user-attachments/assets/4165a30e-6c1b-404c-9fbf-3feaa32ebc89)

I am receiving the above error when I try to copy the specified dll file from the zip to the plugins/misc folder. I am running Windows 11 Pro, is this the cause of this error? If so, is there an alternative for Windows 11?

**Comment by spmn** [comment]
That error is unrelated to this project.

Before copying the file, make sure that VLC is closed and you have write permissions for the destination folder. VLC, by default, is installed in Program Files, which is write-protected.

**Comment by mysticmst** [comment]
Issue resolved after allowing permissions, apparently I didn't allow the modify permission previously.
